servlet api update
jakartaee/jakartaee-tutorial pull request #127
Opened 2024-11-01 14:10 UTC by jhammen

from #74

* Add a NOTE section that explains that previously deprecated methods are now removed in Servlet 6.0, and link to the list of methods: https://jakarta.ee/specifications/servlet/5.0/apidocs/deprecated-list.html
* Add a link to the Servlet 6 release notes: https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/Top-5-things-to-know-about-the-Jakarta-Servlet-60-API-release
* Update the spec URL to point to the Servlet 6 spec: https://jakarta.ee/specifications/servlet/6.0/.
*  it would also be nice to add a couple sentences about the new feature to get a UUID and other connection details for an incoming request

2025-04-18 20:44 UTC, kito99 requested changes
Thanks! Needs one minor change.

2025-04-18 20:44 UTC, kito99 commented on src/main/antora/modules/web/pages/servlets/servlets018.adoc
> +https://jakarta.ee/specifications/servlet/5.0/apidocs/deprecated-list.html[^].
should be /servlet/6.0

2025-04-18 20:52 UTC, kito99 approved these changes

2025-04-21 16:29 UTC, jhammen commented on src/main/antora/modules/web/pages/servlets/servlets018.adoc
> +https://jakarta.ee/specifications/servlet/5.0/apidocs/deprecated-list.html[^].
these were deleted in 6.0 but deprecated in 5.0 - I updated the text to make that more clear

2025-04-21 17:05 UTC, merged